library(ape)
library(MASS)
library(mvtnorm)
library(caper)
setwd("Path_to/Data.txt")
data <- read.table("Data.txt",sep = "\t",header = TRUE)
Tree <- read.tree("Tree.phy")
AGT <- comparative.data(phy=Tree,data=data,names.col = Name,vcv = TRUE,na.omit = FALSE,warn.dropped = TRUE)
result <- pgls(Efficiency~Diet,data = AGT,lambda = 'ML')
summary(result)
plot((data[,c("Diet","Efficiency")]),ylim=c(0,1),col = rgb(128,128,128,180,maxColorValue =255),pch=16,cex=6)
abline(a = coef(result)[1],b = coef(result)[2])
